### ISSUE TITLE
segmentation violation: github.com/lrita/runtime2.Hash(...) on macos

### ISSUE THREAD

**Issue by sergey-kurenkov** [lrita/cmap#1]
I am running your example with go 1.15:

```
$ cat use_cmap.go 
package main

import "github.com/lrita/cmap"

func main() {
	// Create a new map.
	var m cmap.Cmap

	// Stores item within map, sets "bar" under key "foo"
	m.Store("foo", "bar")

	// Retrieve item from map.
	if tmp, ok := m.Load("foo"); ok {
		_ = tmp.(string)
	}

	// Deletes item under key "foo"
	m.Delete("foo")
}
```

```
$ go run use_cmap.go
unexpected fault address 0x30250c8b4865
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30250c8b4865 pc=0x30250c8b4865]

goroutine 1 [running]:
runtime.throw(0x109fe0c, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000066ea0 sp=0xc000066e70 pc=0x1030112
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:727 +0x3e5 fp=0xc000066ed0 sp=0xc000066ea0 pc=0x1044245
github.com/lrita/runtime2.Hash(...)
	/Users/sergey.kurenkov/go/pkg/mod/github.com/lrita/runtime2@v0.0.0-20191126063648-27f28289eda0/eface.go:24
github.com/lrita/cmap.(*Cmap).Store(0xc00000c060, 0x1089d80, 0x10ba9d0, 0x1089d80, 0x10ba9e0)
	/Users/sergey.kurenkov/go/pkg/mod/github.com/lrita/cmap@v0.0.0-20200528161318-ecc156513b0e/cmap.go:48 +0x57 fp=0xc000066f40 sp=0xc000066ed0 pc=0x107ee57
main.main()
	/Users/sergey.kurenkov/go/src/use_cmap/use_cmap.go:10 +0x6d fp=0xc000066f88 sp=0xc000066f40 pc=0x108032d
runtime.main()
	/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc000066fe0 sp=0xc000066f88 pc=0x10328e9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x105fe81
exit status 2
```

```
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sergey.kurenkov/Library/Caches/go-build"
GOENV="/Users/sergey.kurenkov/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sergey.kurenkov/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sergey.kurenkov/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sergey.kurenkov/go/src/use_cmap/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8k/wmd646w54nb94_rfs6l1rn312bkjmr/T/go-build588630850=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by lrita** [comment]
This issue is fixed by new commit, you can have a try.
